### ISSUE TITLE
how to train a Scale 2 network

### ISSUE THREAD

**Issue by ningbende** [researchmm/TTSR#11]
Thanks for your great work.
I want to train a Scale 2 network, eg. 1920x1080->3840x2160.
what should I modified the code?
Thanks

**Comment by FuzhiYang** [comment]
Currently, our code only supports x4 upscale factor. If you want to train other scale factors (e.g. x2), roughly you need to do such changes:
1. Use another backbone which is proper to the new scale factor.
2. Modify texture transformers to transfer textures of proper resolution scales.
3. Modify CSFI modules to do proper information exchange

**Comment by ningbende** [comment]
Thanks for your reply. I will Try
