### ISSUE TITLE
Fold and Unfold

### ISSUE THREAD

**Issue by htzheng** [researchmm/TTSR#13]
In the code, I saw the reference feature map is unfolded into patches, then folded back to feature map. I'm not sure why fold and unfold is necessary, because it seems to be equivalent to just transfer the feature map

```
        ref_lv3_unfold = F.unfold(ref_lv3, kernel_size=(3, 3), padding=1)
        T_lv3_unfold = self.bis(ref_lv3_unfold, 2, R_lv3_star_arg)
        T_lv3 = F.fold(T_lv3_unfold, output_size=lrsr_lv3.size()[-2:], kernel_size=(3,3), padding=1) / (3.*3.)
```

**Comment by FuzhiYang** [comment]
Between unfold and fold, there is a bis (batch index select) step. This step is used to transfer Ref's feature map according to "R_lv3_star_arg". In other words, we transfer feature patches according to the index of the most relevant position.
