### ISSUE TITLE
about Qualitative Evaluation.

### ISSUE THREAD

**Issue by scutlrr** [researchmm/TTSR#15]
在Figure 5中，其他SR方法是直接对 cufed/train/input 中的HR下采样的LR进行超分就可以吗

**Comment by scutlrr** [comment]
还是说用对应的数据集重新训练其他SR方法呢？

**Comment by FuzhiYang** [comment]
我们把所有的模型在CUFED5 train set上进行训练。如果是SISR模型，只用到了input，如果是RefSR模型，input和ref都用到。

**Comment by scutlrr** [comment]
sorry，论文的小细节没关注到~感谢您的回复！
