### ISSUE TITLE
dataset/train/ref/test

### ISSUE THREAD

**Issue by axiniu** [researchmm/TTSR#2]
Thank you  for your work.
I have a trouble when I run thecod.
The datasse I downloaded is not divided to train、ref、test.
Would you share how to divide the data？Thank you very much.

**Comment by FuzhiYang** [comment]
Hi, our used CUFED dataset is also downloaded from SRNTT authors, and the structure is:
--CUFED
    --train
        --input
        --ref
    --test
        --CUFED5

There are 11871 images in "train/input" and "train/ref". And there are 126 test images in "test/CUFED5" with each test image accompanied with five reference images.

Could you show me the latest dataset structure?

**Comment by FuzhiYang** [comment]
I've just updated the dataset link, sorry to give the wrong link before. Now you can use the latest provided link to prepare your dataset. Feel free to contact us if you have other questions.
