### ISSUE TITLE
imageio and nvidia GPU missing from requirements in Readme.md

### ISSUE THREAD

**Issue by mtedaldi** [researchmm/TTSR#22]
Hello

While trying to run test.sh I run into both of those problems.
installing imageio is easily done with pip3 install imageio
getting an nvidia card is a bit more of a hassle...

I've added "--cpu TRUE " to test.sh and now it doesn't error out immediately anymore...

**Comment by FuzhiYang** [comment]
Thanks for your advice. We've added the missing requirements in README file. And I fixed some bugs when running on CPU.
