### ISSUE TITLE
ref1+ref2+ref3+ref4+ref5 -> 27.01?

### ISSUE THREAD

**Issue by flybiubiu** [researchmm/TTSR#25]
ref1 = []
                ref2 = []
                ref3 = []
                ref4 = []
                ref5 = []
                for i_batch, sample_batched in enumerate(self.dataloader['test']['1']):
                    ref1.append(sample_batched['Ref'])
                for i_batch, sample_batched in enumerate(self.dataloader['test']['2']):
                    ref2.append(sample_batched['Ref'])
                for i_batch, sample_batched in enumerate(self.dataloader['test']['3']):
                    ref3.append(sample_batched['Ref'])
                for i_batch, sample_batched in enumerate(self.dataloader['test']['4']):
                    ref4.append(sample_batched['Ref'])
                for i_batch, sample_batched in enumerate(self.dataloader['test']['5']):
                    ref5.append(sample_batched['Ref'])
                Ref = []
                for i in range(126):
                    img = np.zeros((1,3, 2500, 500))
                    h1, w1 = ref1[i].shape[2:]
                    #print(ref1[i].shape)
                    h2, w2 = ref2[i].shape[2:]
                    h3, w3 = ref3[i].shape[2:]
                    h4, w4 = ref4[i].shape[2:]
                    h5, w5 = ref5[i].shape[2:]
                    img[:,:,0:h1, 0:w1] = ref1[i]
                    img[:,:,500:h2+500, 0:w2] = ref2[i]
                    img[:,:,1000:h3+1000, 0:w3] = ref3[i]
                    img[:,:,1500:h4+1500, 0:w4] = ref4[i]
                    img[:,:,2000:h5+2000, 0:w5] = ref5[i]
                    img = torch.from_numpy(img)
                    Ref.append(img)

                    #self.dataloader['test']['1']

                for i_batch, sample_batched in enumerate(self.dataloader['test']['1']):
                    cnt += 1
                    sample_batched = self.prepare(sample_batched)
                    lr = sample_batched['LR']
                    lr_sr = sample_batched['LR_sr']
                    hr = sample_batched['HR']
                    sample_batched['Ref'] = Ref[i_batch].float().to(self.device)
                    ref = sample_batched['Ref']
                    ref_sr = sample_batched['Ref_sr']

<img width="489" alt="Screen Shot 2020-10-28 at 4 45 02 PM" src="https://user-images.githubusercontent.com/20927755/97412767-f4c1b600-193c-11eb-9757-251f330532ea.png">
Thanx! What wrong with it?

**Comment by scutlrr** [comment]
the ref_sr=ref(downscale+upscale), instead of sample_batch['ref_sr']
you need to use resize function to process ref

**Comment by flybiubiu** [comment]
> the ref_sr=ref(downscale+upscale), instead of sample_batch['ref_sr']
> you need to use resize function to process ref
Thx!Thx!Get the right value!
Thx author help!

**Comment by scutlrr** [comment]
> > the ref_sr=ref(downscale+upscale), instead of sample_batch['ref_sr']
> > you need to use resize function to process ref
> > Thx!Thx!Get the right value!
> > Thx author help!

In fact, I am not the author...

**Comment by flybiubiu** [comment]
> > > the ref_sr=ref(downscale+upscale), instead of sample_batch['ref_sr']
> > > you need to use resize function to process ref
> > > Thx!Thx!Get the right value!
> > > Thx author help!
> 
> In fact, I am not the author...

hahha!This problem also be helped with author with chat tool. 
Also,your suggestion is sure right!

**Comment by huaxinxiao** [comment]
@flybiubiu
@scutlrr 
It seems how to simultaneously calculate the five references not very clear? Could you provide some examples?
