### ISSUE TITLE
question about attention design choice

### ISSUE THREAD

**Issue by btwbtm** [researchmm/TTSR#26]
Hi, nice work! I have a simple question. To my understanding, when generating attention map, most work calculate a one-to-one relevance score for each pixel (of feature map) pair. However, you use F.fold and F.unfold to calculate scores between 3*3 windows. Can you give more explaination on this design choice? Thx!

**Comment by FuzhiYang** [comment]
A larger patch will encourage more accurate search and transfer. 3*3 window is better than 1*1. And due to the CUDA memory consideration, we no longer enlarge the patch window size.

**Comment by btwbtm** [comment]
Thanks for your reply.
