### ISSUE TITLE
About learnable texture extractor

### ISSUE THREAD

**Issue by GangMieYe** [researchmm/TTSR#29]
Hi, you said you designed a learnable texture extractor instead of using a pretrained model like vgg in your paper,however in your code,the LTE model is still a pretrained vgg-19.Is there something wrong with your code?

**Comment by FuzhiYang** [comment]
We use VGG19 to initilize the LTE, LTE can be trained end-to-end during the whole network training. This initilization will make convergence faster and improve performance of LTE.
