### ISSUE TITLE
How to train,eval and test on other datasets ?

### ISSUE THREAD

**Issue by Gamkiu** [researchmm/TTSR#30]
It's a great work! How could I train, evaluate and test the Texture Transformer on other datasets like Sun80,Urban100 and Manga109? I can't find the scripts related to this and how to prepare the other datasets for this? thank you!

**Comment by FuzhiYang** [comment]
1. For training on your own datasets, you can refer to CUFED5 train set structure. Our code supports such structure to train on other datasets. 
2. For eval on other datasets, you may modify "evaluate" function in trainer.py. Current code supports on CUFED5 test set. You can refer to this.
3. For test, our test.sh is for demo show which receives single LR and single Ref to output the SR result.
