### ISSUE TITLE
test/train

### ISSUE THREAD

**Issue by hbw945** [researchmm/TTSR#34]
Hello, can 'test/train' specify a gpu to run？ where to set it？And look forward to your reply！

**Comment by FuzhiYang** [comment]
You can add <CUDA_VISIBLE_DEVICES="0"> before the command. For example:

CUDA_VISIBLE_DEVICES="0" sh test.sh

**Comment by hbw945** [comment]
Thank you for your reply, which perfectly solved my problem！

**Comment by hbw945** [comment]
And can you tell me how long is the training time？Thank you

**Comment by FuzhiYang** [comment]
Training time is about one day.

**Comment by hbw945** [comment]
I'm not ready for the test part of my data set. Now in the training stage, I've commented out the evaluate function of the trainer. Is this feasible and will it have any impact? Looking forward to your reply！

**Comment by FuzhiYang** [comment]
You can check whether the path of CUFED test set is right or not. This error usually occurs when this path is set wrong.

**Comment by hbw945** [comment]
Sorry, can you point out in which file I should modify the test path? Thank you again！！！！
