### ISSUE TITLE
Transferal perceptual loss

### ISSUE THREAD

**Issue by kligvasser** [researchmm/TTSR#4]
First, thank you for sharing. It is really impressive work.
Maybe I misunderstood but in section 3.3, the transferal perceptual loss is described whereas T is the target. However, in the code I see that you don't compute gradients for SR, meaning that SR is the target. Am I wrong? my feeling goes with the paper claim.

**Comment by FuzhiYang** [comment]
The insight of the transferal perceptual loss is that this loss constraints the textures of SR similar to the transferred textures T, where T is indeed the target.
In our code, from this line [https://github.com/researchmm/TTSR/blob/master/trainer.py#L96], you can find the gradients are computed from the generated SR.
