### ISSUE TITLE
Regarding low-resolution image restoration without using high-resolution images (ref)

### ISSUE THREAD

**Issue by 2805413893** [researchmm/TTSR#40]
Hello author!  I would like to ask the following about the test, if you do not use the reference image (ref), but only input the ground resolution image (lr), can image restoration be completed?  If you can hope that you can explain the specific method, thanks!

**Comment by amirhosseinghdv** [comment]
HI @FuzhiYang 
What can we do if we don't want to set ground for test stage? I mean we only want our LR image to enhance without having a ground truth.
Thanks
