### ISSUE TITLE
Test without a ground truth and only by an LR image

### ISSUE THREAD

**Issue by amirhosseinghdv** [researchmm/TTSR#46]
HI @FuzhiYang 
What can we do if we don't want to set ground for test stage? I mean we only want our LR image to enhance without having a ground truth.
Thanks

_Originally posted by @amirhosseinghdv in https://github.com/researchmm/TTSR/issues/40#issuecomment-974662726_

**Comment by FuzhiYang** [comment]
You can refer "Quick test" part in README.md
