### ISSUE TITLE
自己的数据集

### ISSUE THREAD

**Issue by sc-huipu-pc** [researchmm/TTSR#49]
我有高分辨率和对应的低分辨率的数据集，怎样做成可训练的数据集？如果像代码中那样都变成160*160的，那岂不是高分辨率和地分辨率的都成了十分模糊的图片

**Comment by GAO293** [comment]
你好，请问你解决此问题了吗

**Comment by s77coolest** [comment]
您好，请问您有论文中提到的数据集CUFED5吗

**Comment by FuzhiYang** [comment]
Our "dataset" code implementation is mainly for CUFED5 dataset. You can refer to this to write your own dataset files and some other necessary modifications to run.

**Comment by hyang0511** [comment]
You can refer to this to download the CUFED5 dataset, the link is from the official release of CUFED and CUFED5:
https://drive.google.com/file/d/1Fa1mopExA9YGG1RxrCZZn7QFTYXLx6ph/view

**Comment by NghiaZun** [comment]
https://drive.google.com/file/d/1Fa1mopExA9YGG1RxrCZZn7QFTYXLx6ph/view
The link seems to be broken. Is there another way to access the file or could you provide a new link?
