### ISSUE TITLE
How to propagate relevance embedding?

### ISSUE THREAD

**Issue by htzheng** [researchmm/TTSR#5]
Thank you for the nice paper! 

In the paper, I saw 

> To reduce the consumption of both time and GPU memory, the relevance embedding is only applied to the smallest scale and further propagated to other scales. 

I wonder how the relevance embedding can be propagated to other scales? Are Q and K are upsampled to a higher resolution for computing r_{i,j}? Or is the similarity matrix r_{i,j} is augmented to a higher resolution in some ways?

Thanks

**Comment by FuzhiYang** [comment]
This is a very good question in technical implementation!

We compute r_{i,j} in the smallest feature resolution scale. And In this smallest scale. The patch size is 3x3 with stride 1. To propagate r_{i,j} to higher feature resolution scales, we will enlarge the unfolded patch size and stride. For example, in 2nd feature resolution scale, the patch size will be 6x6 with stride 2, while in the largest feature resolution scale, the patch size will be 12x12 with stride 4. 

In such a design, we can just compute r_{i,j} in the smallest feature resolution scale to save time and memory.

**Comment by htzheng** [comment]
Thank you for the quick response, it really explains a lot! A following up question is: does it mean that at 2x scale, unfolding with patch size 6x6 and stride 2 is only computed for V, but not Q and K? 

Thanks in advance!

**Comment by FuzhiYang** [comment]
Yes. This can be understood that search only at the smallest scale, while transfer at all 3 scales.
