### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by yangfan97** [researchmm/TTSR#8]
Thank you for your advice about changing the backbone. 
If we use RCAN as the backbone, is it still necessary to use CSFI mudule?

**Comment by FuzhiYang** [comment]
RCAN is not a progressive upsampling architecture. Its feature forwarding is most in the LR scale and with a upsampler in the last few layers. Therefore, CSFI may be not proper to such architecture if you use RCAN as backbone without any changes.
