### ISSUE TITLE
How to train my dataset

### ISSUE THREAD

**Issue by InstantWindy** [researchmm/TTSR#9]
Hi. I want to use this repro to train my own dataset, but how to generate ref data? How to preprocess my dataset? Thanks

**Comment by FuzhiYang** [comment]
Actually, the dataset used in our paper is CUFED5, which is proposed and made by CVPR2019 SRNTT authors. They roughly describe the process of preparing data. You can refer theirs.
From my personal point of view, your prepared dataset should contains image pairs whose lr and ref are similar to let the model learn to utilize ref information.

**Comment by InstantWindy** [comment]
Thank for your reply. But there is a issue about my dataset. My dataset format is: the pixels of LR and HR images are not aligned, and the resolution is not proportional, but the contents of LR and HR images are almost the same. Thanks.

**Comment by FuzhiYang** [comment]
If the resolution is not proportional, you can cut border a little to make its resolution proper for x4 or other scale factor. Besides, you can generate LR from HR by bicubic interpolation by yourself to make them aligned. For Ref data, it may be not so proper if the Ref and HR are almost the same acrosss the whole dataset.
